In [119]:
import pandas as pd
female_file = "female.csv"
male_file = "male.csv"

In [120]:
female_data = pd.read_csv(female_file)
male_data = pd.read_csv(male_file)

In [121]:
male_data.head()

,subjectid,abdominalextensiondepthsitting,acromialheight,acromionradialelength,anklecircumference,axillaheight,balloffootcircumference,balloffootlength,biacromialbreadth,bicepscircumferenceflexed,...,Branch,PrimaryMOS,SubjectsBirthLocation,SubjectNumericRace,Ethnicity,DODRace,Age,Heightin,Weightlbs,WritingPreference
0,10027,266,1467,337,222,1347,253,202,401,369,...,Combat Arms,19D,North Dakota,1,NaN,1,41,71,180,Right hand
1,10032,233,1395,326,220,1293,245,193,394,338,...,Combat Support,68W,New York,1,NaN,1,35,68,160,Left hand
2,10033,287,1430,341,230,1327,256,196,427,408,...,Combat Support,68W,New York,2,NaN,2,42,68,205,Left hand
3,10092,234,1347,310,230,1239,262,199,401,359,...,Combat Service Support,88M,Wisconsin,1,NaN,1,31,66,175,Right hand
4,10093,250,1585,372,247,1478,267,224,435,356,...,Combat Service Support,92G,North Carolina,2,NaN,2,21,77,213,Right hand

In [122]:
male_data.tail()

,subjectid,abdominalextensiondepthsitting,acromialheight,acromionradialelength,anklecircumference,axillaheight,balloffootcircumference,balloffootlength,biacromialbreadth,bicepscircumferenceflexed,...,Branch,PrimaryMOS,SubjectsBirthLocation,SubjectNumericRace,Ethnicity,DODRace,Age,Heightin,Weightlbs,WritingPreference
4077,29442,235,1353,312,216,1263,228,193,384,318,...,Combat Arms,11B,Colorado,51,Blackfoot Cherokee Choctaw,1,22,67,160,Right hand
4078,29443,247,1473,336,234,1346,253,196,428,374,...,Combat Arms,91B,Oklahoma,1,NaN,1,22,71,194,Right hand
4079,29447,264,1394,313,227,1280,245,193,407,367,...,Combat Arms,13B,Oklahoma,1,NaN,1,23,67,186,Right hand
4080,29451,203,1417,327,223,1314,250,196,419,365,...,Combat Arms,13P,Oklahoma,1,NaN,1,22,69,165,Right hand
4081,29452,327,1523,358,226,1408,269,225,442,379,...,Combat Arms,92Y,Oklahoma,1,NaN,1,38,73,218,Right hand

In [123]:
male_data.describe()

,subjectid,abdominalextensiondepthsitting,acromialheight,acromionradialelength,anklecircumference,axillaheight,balloffootcircumference,balloffootlength,biacromialbreadth,bicepscircumferenceflexed,...,waistfrontlengthsitting,waistheightomphalion,weightkg,wristcircumference,wristheight,SubjectNumericRace,DODRace,Age,Heightin,Weightlbs
count,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,...,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000,4082.000000
mean,20003.370897,254.650906,1440.736894,335.244488,229.343949,1329.082068,252.017148,200.935081,415.675649,358.135718,...,387.642822,1056.485301,855.239588,175.916707,847.511514,8.973542,1.534052,30.158991,70.035767,188.004900
std,6568.435122,37.327178,63.287242,17.482795,14.649102,59.516123,12.936131,10.470947,19.161654,34.618093,...,29.349007,52.154671,142.206992,8.955055,41.655628,83.012638,0.958815,8.810118,2.947419,29.941869
min,10027.000000,163.000000,1194.000000,270.000000,156.000000,1106.000000,186.000000,156.000000,337.000000,246.000000,...,293.000000,876.000000,393.000000,141.000000,695.000000,1.000000,1.000000,17.000000,60.000000,0.000000
25%,14270.250000,227.000000,1398.000000,324.000000,219.250000,1289.000000,243.000000,194.000000,403.000000,335.000000,...,367.000000,1020.000000,756.000000,170.000000,819.000000,1.000000,1.000000,23.000000,68.000000,168.000000
50%,17236.500000,251.000000,1439.000000,335.000000,228.000000,1328.000000,252.000000,201.000000,415.000000,357.000000,...,386.000000,1055.000000,846.000000,176.000000,847.000000,1.000000,1.000000,28.000000,70.000000,185.000000
75%,27315.750000,279.000000,1481.000000,346.000000,239.000000,1367.000000,261.000000,208.000000,428.000000,380.000000,...,407.000000,1090.000000,944.000000,182.000000,875.000000,2.000000,2.000000,36.000000,72.000000,207.000000
max,29452.000000,451.000000,1683.000000,393.000000,293.000000,1553.000000,306.000000,245.000000,489.000000,490.000000,...,494.000000,1245.000000,1442.000000,216.000000,1009.000000,4251.000000,8.000000,58.000000,94.000000,321.000000

In [124]:
female_data.head()

,SubjectId,abdominalextensiondepthsitting,acromialheight,acromionradialelength,anklecircumference,axillaheight,balloffootcircumference,balloffootlength,biacromialbreadth,bicepscircumferenceflexed,...,Branch,PrimaryMOS,SubjectsBirthLocation,SubjectNumericRace,Ethnicity,DODRace,Age,Heightin,Weightlbs,WritingPreference
0,10037,231,1282,301,204,1180,222,177,373,315,...,Combat Support,92Y,Germany,2,NaN,2,26,61,142,Right hand
1,10038,194,1379,320,207,1292,225,178,372,272,...,Combat Service Support,25U,California,3,Mexican,3,21,64,120,Right hand
2,10042,183,1369,329,233,1271,237,196,397,300,...,Combat Service Support,35D,Texas,1,NaN,1,23,68,147,Right hand
3,10043,261,1356,306,214,1250,240,188,384,364,...,Combat Service Support,25U,District of Columbia,8,Caribbean Islander,2,22,66,175,Right hand
4,10051,309,1303,308,214,1210,217,182,378,320,...,Combat Arms,42A,Texas,1,NaN,1,45,63,195,Right hand

In [125]:
female_data.tail()

,SubjectId,abdominalextensiondepthsitting,acromialheight,acromionradialelength,anklecircumference,axillaheight,balloffootcircumference,balloffootlength,biacromialbreadth,bicepscircumferenceflexed,...,Branch,PrimaryMOS,SubjectsBirthLocation,SubjectNumericRace,Ethnicity,DODRace,Age,Heightin,Weightlbs,WritingPreference
1981,29501,285,1392,335,223,1297,252,196,368,299,...,Combat Support,42A,Texas,3,Mexican,3,51,67,180,Right hand
1982,29502,262,1324,301,202,1204,236,181,378,294,...,Combat Support,25U,Texas,3,Mexican,3,40,63,150,Right hand
1983,29503,260,1334,318,213,1259,234,183,363,332,...,Combat Support,42A,Texas,2,NaN,2,40,66,168,Right hand
1984,29511,205,1293,302,199,1207,213,163,376,276,...,Combat Support,92Y,Texas,3,Mexican,3,31,63,133,Right hand
1985,920103,238,1346,308,210,1256,236,188,361,285,...,Combat Support,92F,Texas,3,Mexican,3,27,66,132,Right hand

In [126]:
female_data.describe()

,SubjectId,abdominalextensiondepthsitting,acromialheight,acromionradialelength,anklecircumference,axillaheight,balloffootcircumference,balloffootlength,biacromialbreadth,bicepscircumferenceflexed,...,waistfrontlengthsitting,waistheightomphalion,weightkg,wristcircumference,wristheight,SubjectNumericRace,DODRace,Age,Heightin,Weightlbs
count,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.00000,1986.000000,1986.000000,...,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000,1986.000000
mean,22306.606244,229.651057,1335.095166,311.198389,215.739678,1239.029708,228.110272,182.05136,365.348943,305.578550,...,355.136455,980.149043,677.582075,154.792548,794.190332,35.072004,1.781470,28.943605,64.601712,147.505035
std,20904.730297,31.464691,58.079885,17.164691,14.891757,55.801958,11.771007,9.64192,18.298851,30.757033,...,23.945046,50.022715,109.846458,7.827695,38.194755,955.582848,0.999536,8.332078,2.801938,22.855371
min,10037.000000,155.000000,1115.000000,249.000000,170.000000,1038.000000,194.000000,151.00000,283.000000,216.000000,...,289.000000,805.000000,358.000000,124.000000,672.000000,1.000000,1.000000,17.000000,56.000000,86.000000
25%,17667.000000,207.000000,1298.000000,300.000000,205.000000,1202.000000,220.000000,175.00000,353.000000,285.000000,...,338.000000,947.000000,601.000000,150.000000,769.000000,1.000000,1.000000,22.000000,63.000000,130.000000
50%,22096.500000,227.000000,1332.000000,311.000000,215.000000,1236.000000,227.000000,182.00000,365.000000,304.000000,...,355.000000,977.500000,668.000000,154.000000,794.000000,2.000000,2.000000,27.000000,64.000000,145.000000
75%,26089.750000,249.000000,1374.000000,323.000000,225.000000,1277.000000,236.000000,188.00000,378.000000,324.000000,...,370.000000,1013.000000,745.750000,160.000000,819.000000,3.000000,2.000000,34.000000,66.000000,161.000000
max,920103.000000,358.000000,1536.000000,371.000000,275.000000,1419.000000,270.000000,216.00000,422.000000,435.000000,...,432.000000,1142.000000,1196.000000,183.000000,941.000000,42351.000000,6.000000,58.000000,80.000000,270.000000

In [127]:
print([x for x in male_data.columns])

['subjectid', 'abdominalextensiondepthsitting', 'acromialheight', 'acromionradialelength', 'anklecircumference', 'axillaheight', 'balloffootcircumference', 'balloffootlength', 'biacromialbreadth', 'bicepscircumferenceflexed', 'bicristalbreadth', 'bideltoidbreadth', 'bimalleolarbreadth', 'bitragionchinarc', 'bitragionsubmandibulararc', 'bizygomaticbreadth', 'buttockcircumference', 'buttockdepth', 'buttockheight', 'buttockkneelength', 'buttockpopliteallength', 'calfcircumference', 'cervicaleheight', 'chestbreadth', 'chestcircumference', 'chestdepth', 'chestheight', 'crotchheight', 'crotchlengthomphalion', 'crotchlengthposterioromphalion', 'earbreadth', 'earlength', 'earprotrusion', 'elbowrestheight', 'eyeheightsitting', 'footbreadthhorizontal', 'footlength', 'forearmcenterofgriplength', 'forearmcircumferenceflexed', 'forearmforearmbreadth', 'forearmhandlength', 'functionalleglength', 'handbreadth', 'handcircumference', 'handlength', 'headbreadth', 'headcircumference', 'headlength', 'heelanklecircumference', 'heelbreadth', 'hipbreadth', 'hipbreadthsitting', 'iliocristaleheight', 'interpupillarybreadth', 'interscyei', 'interscyeii', 'kneeheightmidpatella', 'kneeheightsitting', 'lateralfemoralepicondyleheight', 'lateralmalleolusheight', 'lowerthighcircumference', 'mentonsellionlength', 'neckcircumference', 'neckcircumferencebase', 'overheadfingertipreachsitting', 'palmlength', 'poplitealheight', 'radialestylionlength', 'shouldercircumference', 'shoulderelbowlength', 'shoulderlength', 'sittingheight', 'sleevelengthspinewrist', 'sleeveoutseam', 'span', 'stature', 'suprasternaleheight', 'tenthribheight', 'thighcircumference', 'thighclearance', 'thumbtipreach', 'tibialheight', 'tragiontopofhead', 'trochanterionheight', 'verticaltrunkcircumferenceusa', 'waistbacklength', 'waistbreadth', 'waistcircumference', 'waistdepth', 'waistfrontlengthsitting', 'waistheightomphalion', 'weightkg', 'wristcircumference', 'wristheight', 'Gender', 'Date', 'Installation', 'Component', 'Branch', 'PrimaryMOS', 'SubjectsBirthLocation', 'SubjectNumericRace', 'Ethnicity', 'DODRace', 'Age', 'Heightin', 'Weightlbs', 'WritingPreference']

In [128]:
print([x for x in female_data.columns])

['SubjectId', 'abdominalextensiondepthsitting', 'acromialheight', 'acromionradialelength', 'anklecircumference', 'axillaheight', 'balloffootcircumference', 'balloffootlength', 'biacromialbreadth', 'bicepscircumferenceflexed', 'bicristalbreadth', 'bideltoidbreadth', 'bimalleolarbreadth', 'bitragionchinarc', 'bitragionsubmandibulararc', 'bizygomaticbreadth', 'buttockcircumference', 'buttockdepth', 'buttockheight', 'buttockkneelength', 'buttockpopliteallength', 'calfcircumference', 'cervicaleheight', 'chestbreadth', 'chestcircumference', 'chestdepth', 'chestheight', 'crotchheight', 'crotchlengthomphalion', 'crotchlengthposterioromphalion', 'earbreadth', 'earlength', 'earprotrusion', 'elbowrestheight', 'eyeheightsitting', 'footbreadthhorizontal', 'footlength', 'forearmcenterofgriplength', 'forearmcircumferenceflexed', 'forearmforearmbreadth', 'forearmhandlength', 'functionalleglength', 'handbreadth', 'handcircumference', 'handlength', 'headbreadth', 'headcircumference', 'headlength', 'heelanklecircumference', 'heelbreadth', 'hipbreadth', 'hipbreadthsitting', 'iliocristaleheight', 'interpupillarybreadth', 'interscyei', 'interscyeii', 'kneeheightmidpatella', 'kneeheightsitting', 'lateralfemoralepicondyleheight', 'lateralmalleolusheight', 'lowerthighcircumference', 'mentonsellionlength', 'neckcircumference', 'neckcircumferencebase', 'overheadfingertipreachsitting', 'palmlength', 'poplitealheight', 'radialestylionlength', 'shouldercircumference', 'shoulderelbowlength', 'shoulderlength', 'sittingheight', 'sleevelengthspinewrist', 'sleeveoutseam', 'span', 'stature', 'suprasternaleheight', 'tenthribheight', 'thighcircumference', 'thighclearance', 'thumbtipreach', 'tibialheight', 'tragiontopofhead', 'trochanterionheight', 'verticaltrunkcircumferenceusa', 'waistbacklength', 'waistbreadth', 'waistcircumference', 'waistdepth', 'waistfrontlengthsitting', 'waistheightomphalion', 'weightkg', 'wristcircumference', 'wristheight', 'Gender', 'Date', 'Installation', 'Component', 'Branch', 'PrimaryMOS', 'SubjectsBirthLocation', 'SubjectNumericRace', 'Ethnicity', 'DODRace', 'Age', 'Heightin', 'Weightlbs', 'WritingPreference']

In [129]:
def div_conversion(df, column, div):
    return df[column].apply(lambda x: x/div)

In [130]:
male_data['stature'] = div_conversion(male_data, 'stature', 1000) # Convert to Meters
male_data['weightkg'] = div_conversion(male_data, 'weightkg', 10) # Convert to Kg
male_data['chestcircumference'] = div_conversion(male_data, 'chestcircumference', 10) # convert to cm 
male_data['waistcircumference'] = div_conversion(male_data, 'waistcircumference', 10) #convert to cm
female_data['stature'] = div_conversion(female_data, 'stature', 1000) # Convert to Meters
female_data['weightkg'] = div_conversion(female_data, 'weightkg', 10) # Convert to Kg
female_data['chestcircumference'] = div_conversion(female_data, 'chestcircumference', 10) # convert to cm 
female_data['waistcircumference'] = div_conversion(female_data, 'waistcircumference', 10) #convert to cm

In [131]:
print(male_data['stature'].describe(),any(male_data['stature'].isnull()))
print(male_data['weightkg'].describe(),any(male_data['weightkg'].isnull()))
print(male_data['chestcircumference'].describe(),any(male_data['chestcircumference'].isnull()))
print(male_data['waistcircumference'].describe(),any(male_data['waistcircumference'].isnull()))

print(female_data['stature'].describe(),any(female_data['stature'].isnull()))
print(female_data['weightkg'].describe(),any(female_data['weightkg'].isnull()))
print(female_data['chestcircumference'].describe(),any(female_data['chestcircumference'].isnull()))
print(female_data['waistcircumference'].describe(),any(female_data['waistcircumference'].isnull()))

count    4082.000000
mean        1.756215
std         0.068551
min         1.491000
25%         1.710000
50%         1.755000
75%         1.802000
max         1.993000
Name: stature, dtype: float64 False
count    4082.000000
mean       85.523959
std        14.220699
min        39.300000
25%        75.600000
50%        84.600000
75%        94.400000
max       144.200000
Name: weightkg, dtype: float64 False
count    4082.000000
mean      105.870554
std         8.743527
min        77.400000
25%        99.600000
50%       105.600000
75%       111.700000
max       146.900000
Name: chestcircumference, dtype: float64 False
count    4082.000000
mean       94.057741
std        11.170587
min        64.800000
25%        85.700000
50%        93.700000
75%       101.600000
max       137.900000
Name: waistcircumference, dtype: float64 False
count    1986.000000
mean        1.628473
std         0.064200
min         1.409000
25%         1.586250
50%         1.626000
75%         1.672000
max         1.829000
Name: stature, dtype: float64 False
count    1986.000000
mean       67.758207
std        10.984646
min        35.800000
25%        60.100000
50%        66.800000
75%        74.575000
max       119.600000
Name: weightkg, dtype: float64 False
count    1986.000000
mean       94.685801
std         8.269911
min        69.500000
25%        88.900000
50%        94.000000
75%        99.900000
max       126.600000
Name: chestcircumference, dtype: float64 False
count    1986.000000
mean       86.090534
std         9.993177
min        61.100000
25%        79.000000
50%        85.200000
75%        92.500000
max       133.400000
Name: waistcircumference, dtype: float64 False

In [220]:
#which parameters are of use: stature, weightkg divide by 10 because americans....., chestcircumference, waistcircumference, waistdepth
def create_sample(df, gender, columns: list, sample_size):
        [list(df.columns).index(column) for column in columns]
        df = df.iloc[:sample_size, [list(df.columns).index(column) for column in columns]].copy()
        df.to_csv(f'{gender}_sample{sample_size}.csv', index=False)

def backup_sample(df, gender, sample_size):
    df.to_csv(f'{gender}_sample{sample_size}.csv', index=False)

In [221]:
create_sample(male_data, 'male', ['chestcircumference', 'waistcircumference'], 100)
create_sample(female_data, 'female', ['chestcircumference', 'waistcircumference'], 100)

In [222]:
df = pd.read_csv('male_sample100.csv')
ff = pd.read_csv('female_sample100.csv')

In [223]:
df.head()

   chestcircumference  waistcircumference
0               107.4                93.3
1               102.1                87.0
2               112.0                96.4
3               111.4                85.7
4               104.8                86.8

In [224]:
ff.head()

   chestcircumference  waistcircumference
0                92.2                85.0
1                83.9                70.8
2                87.4                72.7
3               100.8                92.3
4               108.9               116.3

Male T-shirt Size Chart by Body Measurement, <br>
CM: SIZE WAIST CHEST <br>
XXS 69-74 cm 74-79 cm <br>
XS 71-76 cm 76-81 cm <br>
S 76-81 cm 86-91 cm <br>
M 81-84 cm 97-102 cm <br>
L 84-87 cm 107-112 cm <br>
XL 91-97 cm 116-122 cm <br>
XXL 102-107 cm 122-127 cm <br>
3XL 112-122 cm 127-132 cm <br>

Female EU SIZE INT. WAIST CHEST<br>
XXS 54-57 cm 70-75 cm <br>
XS 58-66 cm 75-81 cm<br>
S 67-71 cm 82-87 cm<br>
M 72-80 cm 89-95 cm<br>
L 81-92 cm 96-105 cm <br>
XL 93-101 cm 106-115 cm<br> 
XXL 101-104 cm 116-122 cm

Chest + waist with correlation between weight + height

In [225]:
men_sizes = {"XXS": [(69, 71), (74, 76)], "XS": [(71, 77), (76, 86)], "S": [(77, 81), (86, 97)], "M": [(81, 85), (97, 107)], "L": [(85, 92), (107, 116)], "XL": [(92, 102), (116, 122)], "XXL": [(102, 112), (122, 128)], "3XL": [(112, 122), (128, 132)]}
female_sizes = {"XSS": [(54, 58), (70, 75)], "XS": [(58, 67), (75,82)], "S": [(67, 72), (82, 89)], "M": [(72, 81), (89, 96)], "L": [(81, 93), (96, 106)], "XL": [(93, 101), (106, 116)], "XXL": [(101, 104), (116, 122)]}

In [226]:
def categories_by_size(df, sizes):
    cloth_sizes = ["L"]
    for row in range(df.shape[0]):
        key_found = False
        for key in sizes:
            for i, col in enumerate(df):
                if sizes[key][i][0] <= df[col][row] <= sizes[key][i][1]:
                    cloth_sizes.append(key)
                    key_found = True
                    break

            if key_found: break

    df["clothingsize"] = cloth_sizes
    return df

In [227]:
categories_by_size(df, men_sizes)

    chestcircumference  waistcircumference clothingsize
0                107.4                93.3            L
1                102.1                87.0            S
2                112.0                96.4            S
3                111.4                85.7            S
4                104.8                86.8           XS
..                 ...                 ...          ...
95                99.4                80.9           XS
96               100.1                86.2            S
97               106.9               102.7            M
98                99.5                79.7           XS
99               110.4               108.2            L

[100 rows x 3 columns]

In [228]:
print(df.columns, '\n')
print(df.count())
print(df)

Index(['chestcircumference', 'waistcircumference', 'clothingsize'], dtype='object')

chestcircumference    100
waistcircumference    100
clothingsize          100
dtype: int64
    chestcircumference  waistcircumference clothingsize
0                107.4                93.3            L
1                102.1                87.0            S
2                112.0                96.4            S
3                111.4                85.7            S
4                104.8                86.8           XS
..                 ...                 ...          ...
95                99.4                80.9           XS
96               100.1                86.2            S
97               106.9               102.7            M
98                99.5                79.7           XS
99               110.4               108.2            L

[100 rows x 3 columns]

In [229]:
def k_nearest_neighbor(df, P, k):
    def vec_abs(vec):
        return sqrt(sum([unit**2 for unit in vec]))
    
    def compute_vec(*args):
        dim = 2
        vectors = [[args[index][row] - args[index-1][row] for row in range(dim)] for index in range(1, len(args))]
        vector = [sum([vec[col] for vec in vectors]) for col in range(dim)] if len(vectors) > 1 else vectors[0]
        return zip(args[0], vector) if len(args) > 2 else zip(args[0], args[1])

    x, y = df.columns
    
    return 0